Repository CrowdStrike/falcon-mcp, pull requests merged in 2025-08, with the labels that each got.

#97 refactor(resources/detections): use new tuple method for fql detections table
  falcon_mcp/resources/detections.py
Labels: refactoring

#103 feat(server): add distinct tools for active vs available modules
  README.md
  falcon_mcp/server.py
  tests/test_server.py
Labels: enhancement

#100 ci: add dependabot scanning
  .github/dependabot.yml
Labels: github-action

#124 feat(modules/idp): Add geolocation info to entities and timeline in i…
  falcon_mcp/modules/idp.py
  tests/modules/test_idp.py
Labels: enhancement
